### Setting up OLTP Database

In [1]:
from sqlalchemy import create_engine , text 
import pandas as pd

In [11]:

conn = create_engine(
    'mysql+mysqlconnector://admin:anish2004@etl-database-oltp.cdw8miqa4k6c.ap-south-1.rds.amazonaws.com'
).connect()

In [3]:
#### creating OLTP DB (mimikin its live updating App DB) and populating it with data from from the CSV files to inserting each row of the CSV files into the respective tables in the OLTP database.

players_df = pd.read_csv('./data/Player.csv')
player_matches_df = pd.read_csv('./data/Player_Match.csv')
deliveries_df = pd.read_csv('./data/Deliveries.csv')

In [4]:
## creating the database on the db sserver 

##The ObjectNotExecutableError you are seeing in the image occurs because recent versions of SQLAlchemy no longer allow passing raw Python strings directly into the execute() method. You must explicitly declare the string as an executable SQL statement.

conn.execute( text("CREATE DATABASE IF NOT EXISTS cricket_oltp;") )


## get which are the databases present in the server


## commiting the changes to the database
conn.commit()

In [12]:
conn.execute(text("SHOW DATABASES;")).fetchall()

[('cricket_oltp',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sys',)]

In [19]:
# show one of the tables in the database
conn.execute(text("SHOW TABLES FROM cricket_oltp;")).fetchall()

[('delivery',), ('player',), ('player_captain',)]

In [7]:

# 1. Create a NEW engine that points directly to your newly created database
# Replace the placeholder credentials with your actual AWS details
db = create_engine('mysql+mysqlconnector://admin:anish2004@etl-database-oltp.cdw8miqa4k6c.ap-south-1.rds.amazonaws.com/cricket_oltp').connect()

In [8]:


# # 3. Now run your Pandas upload using the NEW connection (db_conn)
# players_df.to_sql('player', con=db, if_exists='replace', index=False)
# player_matches_df.to_sql('player_captain', con=db, if_exists='replace', index=False)


## deliveries_df.info() ## 33.8+ MB ## 1426312 rows 

## calcutaion for oplitmal chunk size for uploading the data to the database

## maximum number of rows to upload in a single chunk = 1000000 / (number of columns * 8 bytes per column) = 1000000 / (20 * 8) = 6250 rows

## 

## uploadding  in chunks of 100 rows to avoid memory issues and to make the upload process more efficient.
deliveries_df.to_sql(
    'delivery', 
    con=db, 
    if_exists='replace', 
    index=False,
    chunksize=5000,  ## numner of rows to upload in a single chunk  ::: Breaks the 1.4 million rows into smaller batches. This prevents RAM exhaustion on your machine and prevents transaction timeouts on your AWS RDS instance.
    method='multi'  ### Instead of sending 5,000 separate INSERT commands over the network, this packages them into one massive INSERT INTO delivery VALUES (...), (...), (...) statement per chunk, drastically reducing network latency.
)

-53

### Extracting The Data from the OLTP Database

In [72]:
db = create_engine('mysql+mysqlconnector://admin:anish2004@etl-database-oltp.cdw8miqa4k6c.ap-south-1.rds.amazonaws.com/cricket_oltp').connect()

In [74]:
player = pd.read_sql_query('SELECT * FROM player',con = db)
delivery = pd.read_sql_query('SELECT * FROM delivery',con = db)
player_captain = pd.read_sql_query('SELECT * FROM player_captain',con = db)

In [75]:
player.head()

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN

In [76]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,None,None,None
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,None,None,None
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,None,None,None

In [77]:
player_captain.head()

   Match_Id  Player_Id  Team_Id  Is_Keeper  Is_Captain
0    335987          1        1          0           1
1    335987          2        1          0           0
2    335987          3        1          0           0
3    335987          4        1          0           0
4    335987          5        1          0           0

In [78]:
temp_df = player.merge(player_captain,on='Player_Id')[['Player_Name','Match_Id','Is_Captain']]

In [79]:
temp_df.head(1)

  Player_Name  Match_Id  Is_Captain
0  SC Ganguly    335987           1

In [80]:
# 1. Run your merge
delivery = delivery.merge(temp_df, left_on=['match_id','batter'],right_on=['Match_Id','Player_Name'],how='left').fillna(0)
# # 2. Drop the redundant '_y' columns from the right table
# delivery = delivery.drop(columns=['Player_Name_y', 'Match_Id_y', 'Is_Captain_y'])
# # 3. Rename the '_x' columns back to their original names
# delivery = delivery.rename(columns={
#     'Player_Name_x': 'Player_Name', 
#     'Match_Id_x': 'Match_Id', 
#     'Is_Captain_x': 'Is_Captain'
# })

In [81]:
delivery.head(3)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,Player_Name,Match_Id,Is_Captain
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,0,0,0,0,0.0,0.0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,0,0,0,0,0,0,0.0,0.0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,0,0,0,0,0.0,0.0

In [82]:
runs = delivery.groupby(['match_id','batter'])['batsman_runs'].sum().reset_index()
balls = delivery.groupby(['match_id','batter'])['batsman_runs'].count().reset_index()

In [83]:
runs

       match_id         batter  batsman_runs
0        335982      AA Noffke             9
1        335982        B Akhil             0
2        335982    BB McCullum           158
3        335982       CL White             6
4        335982      DJ Hussey            12
...         ...            ...           ...
16510   1426312      SP Narine             6
16511   1426312        SS Iyer             6
16512   1426312  Shahbaz Ahmed             8
16513   1426312        TM Head             0
16514   1426312        VR Iyer            52

[16515 rows x 3 columns]

In [87]:
balls

       match_id         batter  batsman_runs
0        335982      AA Noffke            12
1        335982        B Akhil             2
2        335982    BB McCullum            77
3        335982       CL White            10
4        335982      DJ Hussey            12
...         ...            ...           ...
16510   1426312      SP Narine             2
16511   1426312        SS Iyer             3
16512   1426312  Shahbaz Ahmed             7
16513   1426312        TM Head             1
16514   1426312        VR Iyer            27

[16515 rows x 3 columns]

In [84]:
fours = delivery.query('batsman_runs == 4').groupby(['match_id','batter'])['batsman_runs'].count().reset_index()
sixes = delivery.query('batsman_runs == 6').groupby(['match_id','batter'])['batsman_runs'].count().reset_index()

In [88]:
final_df = runs.merge(balls,on=['match_id','batter'],suffixes=('_runs','_balls')).merge(fours,on=['match_id','batter'],how='left').merge(sixes,on=['match_id','batter'],how='left')
final_df.head(3)

,match_id,batter,batsman_runs_runs,batsman_runs_balls,batsman_runs_x,batsman_runs_y
0,335982,AA Noffke,9,12,1.0,NaN
1,335982,B Akhil,0,2,NaN,NaN
2,335982,BB McCullum,158,77,10.0,13.0

In [89]:
final_df.fillna(0,inplace=True)

In [95]:
final_df.rename(columns={
    'batsman_runs_runs':'runs',
    'batsman_runs_balls':'balls',
    'batsman_runs_x':'fours',
    'batsman_runs_y':'sixes'
},inplace=True)

In [96]:
final_df.head(3)

   match_id       batter  runs  balls  fours  sixes
0    335982    AA Noffke     9     12    1.0    0.0
1    335982      B Akhil     0      2    0.0    0.0
2    335982  BB McCullum   158     77   10.0   13.0

In [97]:
final_df['sr'] = round((final_df['runs']/final_df['balls'])*100,2)

In [98]:
final_df.drop(columns=['balls'],inplace=True)

In [100]:
final_df = final_df.merge(temp_df,left_on=['match_id','batter'],right_on=['Match_Id','Player_Name'],how='left').drop(columns=['Player_Name','Match_Id']).fillna(0)

In [102]:
final_df = final_df.merge(balls,on=['match_id','batter']).rename(columns={'batsman_runs':'balls'})

In [104]:
final_df

       match_id         batter  runs  fours  sixes      sr  Is_Captain  balls
0        335982      AA Noffke     9    1.0    0.0   75.00         0.0     12
1        335982        B Akhil     0    0.0    0.0    0.00         0.0      2
2        335982    BB McCullum   158   10.0   13.0  205.19         0.0     77
3        335982       CL White     6    0.0    0.0   60.00         0.0     10
4        335982      DJ Hussey    12    1.0    0.0  100.00         0.0     12
...         ...            ...   ...    ...    ...     ...         ...    ...
16510   1426312      SP Narine     6    0.0    1.0  300.00         0.0      2
16511   1426312        SS Iyer     6    1.0    0.0  200.00         0.0      3
16512   1426312  Shahbaz Ahmed     8    0.0    1.0  114.29         0.0      7
16513   1426312        TM Head     0    0.0    0.0    0.00         0.0      1
16514   1426312        VR Iyer    52    4.0    3.0  192.59         0.0     27

[16515 rows x 8 columns]

In [106]:
def dream11(row):
  score = 0

  score = score + row['runs'] + row['fours'] + 2*row['sixes']

  if row['runs'] >= 100:
    score = score + 16
  elif row['runs'] >= 50 and row['runs'] < 100:
    score = score + 8
  elif row['runs'] >= 30 and row['runs'] < 50:
    score = score + 4
  elif row['runs'] == 0:
    score = score - 2

  if row['balls'] >= 10:
    if row['sr'] > 170:
      score = score + 6
    elif row['sr'] > 150 and row['sr'] <= 170:
      score = score + 4
    elif row['sr'] > 130 and row['sr'] <= 150:
      score = score + 2
    elif row['sr'] > 60 and row['sr'] <= 70:
      score = score - 2
    elif row['sr'] > 50 and row['sr'] <= 60:
      score = score - 4
    elif row['sr'] <= 50:
      score = score - 6
    else:
      pass

  if row['Is_Captain'] == 1:
    score = score*2


  return score

In [107]:
final_df['score'] = final_df.apply(dream11,axis=1)

In [109]:
export_df = final_df.sort_values('score',ascending=False)[['match_id','batter','score']]

In [111]:
export_df.to_csv("./final_output.csv",index=False)

### Loading the Data into OLAP Database

In [116]:
from sqlalchemy import create_engine , text
import pandas as pd

In [117]:
df = pd.read_csv('./final_output.csv')

In [118]:
df.head(2)

   match_id        batter  score
0    501243      V Sehwag  332.0
1    501210  SR Tendulkar  272.0

In [120]:
### create db object
db = create_engine("mysql+mysqlconnector://admin:anish2004@etl-database-oltp.cdw8miqa4k6c.ap-south-1.rds.amazonaws.com/cricket_oltp").connect()

In [121]:
## upload the final output to the OLAP database
df.to_sql('dream11_score', con=db, if_exists='replace', index=False , chunksize=5000, method='multi')

-4

In [124]:
## Testing if the data is uploaded successfully or not by bringing the data from the OLAP database
df_olap = pd.read_sql_query('SELECT * FROM dream11_score',con = db)
df_olap.shape

(16515, 3)