### About Plotly

Plotly is a Data Viz library by the company Plotly based out of Canada with support in languages such as Python, Js, Julia etc.

#### Advantages

- Multi language support
- Lot's of graphs
- Interactive plots
- Beautiful plots

Does not work with live data streams. Dash can be explored for that.

### The Plotly Roadmap

- Plotly Go (Graph objects) - original library for creating plots in Poltly , but its not very user friendly and requires a lot of code to create plots. It is still used for creating complex plots.
- Plotly Express - A high level wrapper around Plotly Go which is very user friendly and requires less code to create plots. It is used for creating simple plots.
- Dash - A framework for building interactive web applications using Plotly. It allows for the creation of dashboards and live data visualizations.

### Working with Plotly Go

In [56]:
# import the libraries
import plotly.graph_objects as go
import plotly.express as px
import numpy as np
import pandas as pd

In [57]:
# import datasets
tips = px.data.tips()
iris = px.data.iris()
gap = px.data.gapminder()

In [58]:
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [59]:
# scatter plot using plotly go

temp_df = gap[gap['year'] == 2007]  ## ONLY 2007 data is taken for the scatter plot
temp_df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32
...,...,...,...,...,...,...,...,...
1655,Vietnam,Asia,2007,74.249,85262356,2441.576404,VNM,704
1667,West Bank and Gaza,Asia,2007,73.422,4018332,3025.349798,PSE,275
1679,"Yemen, Rep.",Asia,2007,62.698,22211743,2280.769906,YEM,887
1691,Zambia,Africa,2007,42.384,11746035,1271.211593,ZMB,894
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [60]:
##  A "trace" object is a single collection of data and its specific visual rendering rules within a figure. In this case we are plotting the life expectancy vs GDP per capita for the year 2007.
## then create data list which contains the traces 
## then create the layout for the plot which contains the title and axis labels. 
## Finally create the figure using the data and layout and show the plot.
## and call the show() method to display the plot.

trace1 = go.Scatter(x=temp_df['lifeExp'],y=temp_df['gdpPercap'],mode='markers')  ## Returns Scatter Trace object with the specified x and y data, and mode set to 'markers' to display points on the scatter plot.
trace2 = go.Scatter(x=[0,1,10],y=[0,1000,30000],mode='lines')  # Returns Scatter Trace object with the specified x and y data, and mode set to 'lines' to display a line on the scatter plot.

data = [trace1,trace2]  # data list contains the two traces created above, which will be used to create the plot differnet traces on a single figure. The first trace represents the scatter plot of life expectancy vs GDP per capita for the year 2007, while the second trace represents a line connecting the points (0,0), (1,1000), and (10,30000).

layout = go.Layout(title='Life Exp Vs GDP per Capita for 2007', xaxis={'title':'Life Exp' , 'color': 'blue'},yaxis={'title':'GDP' , 'color': 'red'})  # layout object defines the overall layout of the plot, including the title and axis labels. The x-axis is labeled as "Life Exp" and colored blue, while the y-axis is labeled as "GDP" and colored red.
fig = go.Figure(data,layout)

fig.show()

In [61]:
temp_df.head(1)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4

In [62]:
# plot life exp and gdp scatter plot -> continent as color -> pop as size -> hover name -> range_x/range_y -> log_x/log_y
px.scatter(temp_df, x='lifeExp', y='gdpPercap',color='continent',size='pop',size_max=100, hover_name='country')

## max size is the paremeter which is used to set the maximum size of the markers in the scatter plot. here we set the maximum size of the markers to 100. if we don't set this parameter then the default value is 20.

In [63]:
gap.head(1)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4

In [64]:
# plot animation of the above curve on the basic of year
px.scatter(gap, x='lifeExp', y='gdpPercap',
           color='continent',size='pop',
           size_max=100, hover_name='country',
           range_x=[10,95],
           animation_frame='year',animation_group='country')

## "animation_frame" is the column which will be used to create the animation. here we passed the year column to create the animation. that means the animation will be created for each year.
## "animation_group" is the column which will be used to group the data. here we passed the country column to group the data. that means the data will be grouped by country and the animation will be created for each country.

In [65]:
# line plot    

### Q.  plot india pop over time line plot

temp_df = gap.loc[gap['country'] == 'India' , : ]
print(temp_df.head(1)) 
px.line(temp_df, x='year', y='pop',title='India population growth',markers=True , labels={'year':'Year','pop':'Population'})

    country continent  year  lifeExp        pop   gdpPercap iso_alpha  iso_num
696   India      Asia  1952   37.373  372000000  546.565749       IND      356

In [66]:
temp_df.head()

    country continent  year  lifeExp        pop   gdpPercap iso_alpha  iso_num
696   India      Asia  1952   37.373  372000000  546.565749       IND      356
697   India      Asia  1957   40.249  409000000  590.061996       IND      356
698   India      Asia  1962   43.605  454000000  658.347151       IND      356
699   India      Asia  1967   47.193  506000000  700.770611       IND      356
700   India      Asia  1972   50.651  567000000  724.032527       IND      356

In [99]:
# plot india china pak  line plot for life-exp over time
temp_df = gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country',values='lifeExp')
temp_df

country     China   India  Pakistan
year
1952     44.00000  37.373    43.436
1957     50.54896  40.249    45.557
1962     44.50136  43.605    47.670
1967     58.38112  47.193    49.800
1972     63.11888  50.651    51.929
1977     63.96736  54.208    54.043
1982     65.52500  56.596    56.158
1987     67.27400  58.553    58.245
1992     68.69000  60.223    60.838
1997     70.42600  61.765    61.818
2002     72.02800  62.879    63.610
2007     72.96100  64.698    65.483

In [100]:
px.line(temp_df, x=temp_df.index, y=temp_df.columns , markers=True, title='Life Expectancy of India, China and Pakistan')

In [101]:
# bar chart
# india's pop over the years
temp_df = gap[gap['country'] == 'India']
px.bar(temp_df,x='year',y='pop')

In [104]:
#### make it wide format data using pivot method where years will be index and countries will be columns 
gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country')

        continent                  lifeExp                          pop  \
country     China India Pakistan     China   India Pakistan       China
year
1952         Asia  Asia     Asia  44.00000  37.373   43.436   556263527
1957         Asia  Asia     Asia  50.54896  40.249   45.557   637408000
1962         Asia  Asia     Asia  44.50136  43.605   47.670   665770000
1967         Asia  Asia     Asia  58.38112  47.193   49.800   754550000
1972         Asia  Asia     Asia  63.11888  50.651   51.929   862030000
1977         Asia  Asia     Asia  63.96736  54.208   54.043   943455000
1982         Asia  Asia     Asia  65.52500  56.596   56.158  1000281000
1987         Asia  Asia     Asia  67.27400  58.553   58.245  1084035000
1992         Asia  Asia     Asia  68.69000  60.223   60.838  1164970000
1997         Asia  Asia     Asia  70.42600  61.765   61.818  1230075000
2002         Asia  Asia     Asia  72.02800  62.879   63.610  1280400000
2007         Asia  Asia     Asia  72.96100  64.698   65.483  1318683096

                                  gdpPercap                            \
country       India   Pakistan        China        India     Pakistan
year
1952      372000000   41346560   400.448611   546.565749   684.597144
1957      409000000   46679944   575.987001   590.061996   747.083529
1962      454000000   53100671   487.674018   658.347151   803.342742
1967      506000000   60641899   612.705693   700.770611   942.408259
1972      567000000   69325921   676.900092   724.032527  1049.938981
1977      634000000   78152686   741.237470   813.337323  1175.921193
1982      708000000   91462088   962.421381   855.723538  1443.429832
1987      788000000  105186881  1378.904018   976.512676  1704.686583
1992      872000000  120065004  1655.784158  1164.406809  1971.829464
1997      959000000  135564834  2289.234136  1458.817442  2049.350521
2002     1034172547  153403524  3119.280896  1746.769454  2092.712441
2007     1110396331  169270617  4959.114854  2452.210407  2605.947580

        iso_alpha                iso_num
country     China India Pakistan   China India Pakistan
year
1952          CHN   IND      PAK     156   356      586
1957          CHN   IND      PAK     156   356      586
1962          CHN   IND      PAK     156   356      586
1967          CHN   IND      PAK     156   356      586
1972          CHN   IND      PAK     156   356      586
1977          CHN   IND      PAK     156   356      586
1982          CHN   IND      PAK     156   356      586
1987          CHN   IND      PAK     156   356      586
1992          CHN   IND      PAK     156   356      586
1997          CHN   IND      PAK     156   356      586
2002          CHN   IND      PAK     156   356      586
2007          CHN   IND      PAK     156   356      586

In [105]:
# pop comp of 3 countries
temp_df = gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country',values='pop')
temp_df

country       China       India   Pakistan
year
1952      556263527   372000000   41346560
1957      637408000   409000000   46679944
1962      665770000   454000000   53100671
1967      754550000   506000000   60641899
1972      862030000   567000000   69325921
1977      943455000   634000000   78152686
1982     1000281000   708000000   91462088
1987     1084035000   788000000  105186881
1992     1164970000   872000000  120065004
1997     1230075000   959000000  135564834
2002     1280400000  1034172547  153403524
2007     1318683096  1110396331  169270617

In [106]:
# grouped bar chart -> text_auto
px.bar(temp_df,x=temp_df.index,y=temp_df.columns)  ## returns a stacked bar chart by default

In [72]:
px.bar(temp_df,x=temp_df.index,y=temp_df.columns , barmode="group" , log_y=True , text_auto=True)  

## log_y is the parameter which is used to set the y-axis to log scale. here we set the y-axis to log scale. if we don't set this parameter then the default value is False.  its mainly used when the data is very large and we want to see the data in log scale. here we set the y-axis to log scale because the population of India, China and Pakistan is very large and we want to see the data in log scale.

In [112]:
# stacked bar chart
# pop contribution per country to a continents pop stacked for a particular year(2007)
temp_df = gap[gap["year"] == 2007]
px.bar(
    temp_df,
    x="continent",
    y="pop",
    color="country",
    labels={
        "pop": "Population [logarithmic Scale]",
        "continent": "Continent",
        "country": "Country",
    },
    title="Population contribution of countries to a continent in 2007",
    log_y=True,
)

In [113]:
gap.head(3)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4

In [114]:
# bar chart animation
px.bar(gap, x='continent',y='pop',color='country',animation_frame='year',animation_group='country',range_y=[0,4000000000])

In [120]:
# histogram
# plot histogram of life expt of all countries in 2007 -> nbins -> text_auto
temp_df = gap[gap['year'] == 2007]
print(temp_df.head(1))

px.histogram(temp_df, x='lifeExp',nbins=10,text_auto=True , labels={'lifeExp':'Life Expectancy (Years)'})

        country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
11  Afghanistan      Asia  2007   43.828  31889923  974.580338       AFG

    iso_num
11        4

In [127]:
px.histogram(iris,x='sepal_length',labels={'sepal_length':'Sepal Length (cm)'},nbins=30,text_auto=True)

In [128]:
# plot histogram of sepal length of all iris species
px.histogram(iris,x='sepal_length',color='species',labels={'sepal_length':'Sepal Length (cm)'},nbins=30,text_auto=True)

In [131]:
# Pie -> values -> names
# find the pie chart of pop of european countries in 2007

temp_df = gap[(gap['year'] == 2007) & (gap['continent'] == 'Europe')]

px.pie(temp_df, values='pop', names='country')

In [136]:
#### find the total population of each continent in 1952
# gap[gap['year'] == 1952].groupby('continent')['pop'].sum()
gap[gap['year'] == 1952].groupby('continent')['pop'].sum().reset_index()

  continent         pop
0    Africa   237640501
1  Americas   345152446
2      Asia  1395357351
3    Europe   418120846
4   Oceania    10686006

In [79]:
# plot pie chart of world pop in 1952 continent wise ->  -> explode(pull)

temp_df = gap[gap['year'] == 1952].groupby('continent')['pop'].sum().reset_index()
px.pie(temp_df, values='pop', names='continent')

In [138]:
# Sunburst plot -> Sunburst plots visualize hierarchical data spanning outwards radially from root to leaves. -> color
# path -> [], values

temp_df = gap[gap['year'] == 2007]

px.sunburst(temp_df, path=['continent','country'],values='pop',color='lifeExp') # hirerachy of Continent(level 0) ---> country (Level 1)

In [139]:
px.sunburst(tips,path=['sex','smoker','day','time'],values='total_bill',color='size')

In [140]:
# Treemap
temp_df = gap[gap['year'] == 2007]

px.treemap(temp_df, path=[px.Constant('World'),'continent','country'],values='pop',color='lifeExp')

In [145]:
# Heatmap -> find heatmap of all continents with year on avg life exp
temp_df = tips.pivot_table(index='day',columns='sex',values='total_bill',aggfunc='mean')
px.imshow(temp_df, text_auto=True, aspect='auto', color_continuous_scale='RdBu', labels={'x':'Sex','y':'Day','color':'Total Bill'})

In [146]:


temp_df = gap.pivot_table(index='year',columns='continent',values='lifeExp',aggfunc='mean')
px.imshow(temp_df)

In [149]:
# 3d scatterplot
# plot a 3d scatter plot of all country data for 2007
temp_df = gap[gap['year'] == 2007]
px.scatter_3d(temp_df, x='lifeExp',y='pop',z='gdpPercap',log_y=True,color='continent',hover_name='country')

In [150]:
px.scatter_3d(iris,x='sepal_length',y='sepal_width',z='petal_length',color='species')

In [151]:
# scatter_matrix -> dimensions
px.scatter_matrix(iris,dimensions=['sepal_length','sepal_width','petal_length','petal_width'],color='species')

In [152]:
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

In [153]:
# facet plot
tips = px.data.tips()
gap = px.data.gapminder()

In [89]:
px.scatter(tips, x='total_bill', y='tip', facet_col='smoker', facet_row='sex',color='time')

## facet is a way to create multiple plots based on the values of one or more categorical variables. In this case, we are creating a scatter plot of total bill vs tip, and we are faceting the plot by smoker and sex. This means that we will have separate plots for each combination of smoker and sex. The facet_col parameter specifies the variable to facet by in the columns, and the facet_row parameter specifies the variable to facet by in the rows. The color parameter specifies the variable to color the points by.

In [158]:
tips.head(1)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

In [157]:
px.histogram(tips,x='total_bill',facet_row='sex' , color="sex")

In [154]:
px.scatter(gap, x='lifeExp', y='gdpPercap', facet_col='year', facet_col_wrap=3)

In [161]:
# 3d Surface plot
# can not be created using Plotly express
# we will use plotly graph object -> go

x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)

xx, yy = np.meshgrid(x,y)

z1 = xx**2 + yy**2
# z3 = np.sin(xx) + np.tan(yy)
z2 = np.sqrt(xx**2 + yy**2)



trace1 = go.Surface(x=x,y=y,z=z1)
trace2 = go.Surface(x=x,y=y,z=z2)

data = [trace1, trace2]

layout = go.Layout(title='3D Surface Plot')

fig = go.Figure(data,layout)

fig.show()

In [165]:
# 3d Surface plot
# can not be created using Plotly express
# we will use plotly graph object -> go

x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)

xx, yy = np.meshgrid(x,y)

z3 = np.sin(xx) + np.tan(yy)




trace3 = go.Surface(x=x, y=y, z=z3)

data = [trace3]

layout = go.Layout(title='3D Surface Plot')

fig = go.Figure(data,layout)

fig.show()

In [167]:
# Contour plot
x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)

xx, yy = np.meshgrid(x,y)

# z = xx**2 + yy**2
z = np.sin(xx) + np.cos(yy)
# z = np.sqrt(xx**2 + yy**2)


trace = go.Contour(x=x,y=y,z=z)

data = [trace]

layout = go.Layout(title='3D Surface Plot of z = sin(x) + cos(y)')

fig = go.Figure(data,layout)

fig.show()

In [168]:
# Subplots
from plotly.subplots import make_subplots

In [169]:
fig = make_subplots(rows=2,cols=2)

In [184]:
fig.add_trace(
    go.Scatter(x=[1,9,5],y=[2,10,1]),
    row = 1,
    col = 1
)

fig.add_trace(
    go.Histogram(x=[1,9,5,22,109,134,56,78,12,34,89] , ),
    row = 1,
    col = 2
)

fig.add_trace(
    go.Scatter(x=[1,9,5,-1],y=[2,10,1.11],mode='markers'),
    row = 2,
    col = 1
)

fig.add_trace(
    go.Histogram(x=[1,9,5,22,109,134,56,78,12,34,89]),
    row = 2,
    col = 2
)

fig.update_layout(title='Subplot Demo')

fig.show()

In [186]:
import plotly.express as px
from plotly.subplots import make_subplots

df = px.data.iris()

fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=[
        "Sepal Length Histogram",
        "Sepal Width Histogram",
        "Petal Length Histogram",
        "Petal Width Histogram"
    ]
)

fig1 = px.histogram(df, x="sepal_length")
fig2 = px.histogram(df, x="sepal_width")
fig3 = px.histogram(df, x="petal_length")
fig4 = px.histogram(df, x="petal_width")

for trace in fig1.data:
    fig.add_trace(trace, row=1, col=1)

for trace in fig2.data:
    fig.add_trace(trace, row=1, col=2)

for trace in fig3.data:
    fig.add_trace(trace, row=2, col=1)

for trace in fig4.data:
    fig.add_trace(trace, row=2, col=2)

fig.show()